<a href="https://colab.research.google.com/github/CHSarada5/python-mini-project/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy - Numeric python
#Most powerful package - Library
#Numpy - Dimensions
#A - One dimensional array
#[A,B] || [A,B] - Two dimensional array - Row || Column
#Three dimensional
#Array - storing, ,anuplating, similar data type
#Faster than any mathematical functions
#Convinient compared to other packages
#Memory efficiency
#supports multi dimensinal arrays
#speed(numpy operations)>speed(list operations)
#size(numpy operations)<size(list operations)
#memory optimization(numpy)>memory optimization(list operations)

In [2]:
#install numpy - pip3

In [3]:
import numpy as np

In [4]:
#create a numpy array
#1D - array

arr1D=np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [5]:
#creating a 2D array
arr2D=np.array([[1,2,3],[4,5,6]])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [6]:
#creating array with default values
allZeroes=np.zeros((2,3))
print(allZeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#creating array with all values of element as '1'
allOnes=np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#creating matrix with all valiues of element as 'constant values-n-full values'
allConstant=np.full((2,3),6)
print(allConstant)

[[6 6 6]
 [6 6 6]]


In [9]:
#creating identity matrix - 1
identityMatrix=np.eye(4)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
#creating random matrices

#with 0 and 1
rand1=np.random.rand(3,3)
print(rand1)

#Between A and B
rand2=np.random.randint(10,20,(3,4))
print(rand2)

[[0.61738603 0.76125574 0.9537451 ]
 [0.90041292 0.49017653 0.01365539]
 [0.08793653 0.47323778 0.94013468]]
[[17 10 14 16]
 [13 15 18 16]
 [11 16 19 10]]


In [11]:
#Array properties
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

#Shape of array
print(f'Th shape of array is{arr.shape}')

#Size of array
print(f'The size of array is{arr.size}')

#DataType of array
print(f'The type of array is{arr.dtype}')

#Dimensions of array
print(f'The dimensions of array is{arr.ndim}')

[[1 2 3]
 [4 5 6]]
Th shape of array is(2, 3)
The size of array is6
The type of array isint64
The dimensions of array is2


In [12]:
#Indexing and Slicing

#access the element in 1D array
arr=np.array([1,2,3])
print(arr)
print(arr[1])

#slicing the elements
print(arr[2:3])

#access the element in 2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1,1])
print(arr2[0:1])
print(arr2[1:0])

[1 2 3]
2
[3]
[[1 2 3]
 [4 5 6]]
5
[[1 2 3]]
[]


In [13]:
#l1=[]
#l1.append(_) for _ in range[10]

l1=np.arange(0,10)

print(l1)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#Mathematical operations

a=np.array([1,2,3])
b=np.array([3,4,5])
print(f'The sum of a and b is{a+b}')
print(f'The difference of a and b is{a-b}')
print(f'The product of a and b is{a*b}')
print(f'The division of a and b is{a/b}')

The sum of a and b is[4 6 8]
The difference of a and b is[-2 -2 -2]
The product of a and b is[ 3  8 15]
The division of a and b is[0.33333333 0.5        0.6       ]


In [15]:
#Matrix multiplication
b1=np.array([[1,2,3],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])
c=np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [16]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [17]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [18]:
import numpy as np

In [23]:
#Recap
arr=np.array([[1,2,3],[4,5,6]])

type(arr)
#Dot product - mxn || nxp
arr1=np.eye(2)

print(arr)
print(arr1)

[[1 2 3]
 [4 5 6]]
[[1. 0.]
 [0. 1.]]


In [24]:
arr1.shape

(2, 2)

In [26]:
result=np.dot(arr1,arr)
print(result)

[[1. 2. 3.]
 [4. 5. 6.]]


In [27]:
r1=np.random.randint(10,20,(3,3))
print(r1)

[[14 19 12]
 [10 10 10]
 [17 18 19]]


In [28]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
result2=np.dot(r2,r1)
print(result2)

[[14. 19. 12.]
 [10. 10. 10.]
 [17. 18. 19.]]


In [30]:
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [31]:
print(t1)
print(t2)

[[5 5 3]
 [3 3 5]
 [4 4 5]]
[[5 3 3]
 [3 3 5]
 [3 4 4]]


In [32]:
#statistical operations
mean=t2.mean()
max=t2.max()
median=np.median(t2)
std=np.std(t2)
var=np.var(t2)

In [34]:
print(mean)
print(max)
print(median)
print(std)
print(var)
print(std*std)

3.6666666666666665
5
3.0
0.816496580927726
0.6666666666666666
0.6666666666666666


In [38]:
#Trignometric functions
#sin(x),cos(x),tan(x),cot(x),cosec(x),sec(x)
angles=np.array([0,15,30,45,60,75,90])
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [39]:
print(angles)

[ 0 15 30 45 60 75 90]


In [40]:
print(result)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]


In [43]:
print(result1)

[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]


In [42]:
print(result2)

[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [44]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapearr=arr.reshape(2,3)
print(reshapearr)
#to convert/flatten any n dim array
flattenedarr=arr.flatten()
print(flattenedarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [46]:
#stacking the data
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

#vertical stacking
arr3=np.vstack((arr1,arr2))
print(f"The shape of arr3 isd {arr3.shape}")
print(arr3)

#horizontal stacking
arr4=np.hstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")
print(arr4)

The shape of arr3 isd (2, 4)
[[ 1  2  3  4]
 [10 20 30 40]]
The shape of arr3 is (2, 4)
[ 1  2  3  4 10 20 30 40]


In [48]:
#filtering
arr=np.array([10,20,30,40,50,60,70,80])

farr=arr[arr>40]
print(farr)

[50 60 70 80]
